<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>conf</string>
	</array>
	<key>name</key>
	<string>nginx</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#string_single_quoted</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment_line</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numeric</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#server_block</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment_line</key>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=(#|\/\/))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.nginx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.nginx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.number-sign.nginx</string>
				</dict>
			</array>
		</dict>
		<key>location_block</key>
		<dict>
			<key>begin</key>
			<string>^(?:\s*)(location)(.*)\s(\{)($)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.structure.identifier.nginx</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.block.nginx.location</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.location.nginx</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.begin.nginx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.end.nginx</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.block.nginx.location</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_single_quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
			</array>
		</dict>
		<key>numeric</key>
		<dict>
			<key>comment</key>
			<string>handles integer and decimal numbers</string>
			<key>match</key>
			<string>(?x:         # turn on extended mode
                  \b          # Be either the beginning of the line, require whitespace
			             -?         # an optional minus
			             (?:
			               0        # a zero
			               |        # ...or...
			               [1-9]    # a 1-9 character
			               \d*      # followed by zero or more digits
			             )
			             (?:
			               (?:
			                 \.     # a period
			                 \d+    # followed by one or more digits
			               )?
			             )?         # make decimal portion optional
                   (
                     [kKmMgG]b? # Do we have a trailing suffix?
                   )?         # 
                   \b
			           )</string>
			<key>name</key>
			<string>constant.numeric.nginx</string>
		</dict>
		<key>server_block</key>
		<dict>
			<key>begin</key>
			<string>(server)\s(\{)($)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.structure.identifier.nginx</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.block.nginx.server</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.begin.nginx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.end.nginx</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.block.nginx.server</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#location_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_single_quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
			</array>
		</dict>
		<key>string_single_quoted</key>
		<dict>
			<key>begin</key>
			<string>(')</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.nginx</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>single quoted strings</string>
			<key>end</key>
			<string>(')|(\n)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.nginx</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.unclosed-string.nginx</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.nginx</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.nginx</string>
	<key>uuid</key>
	<string>DD4164EB-E7D8-42A9-93E2-8C50411FB4D0</string>
</dict>
</plist>
